name: helloworld_workflow

on: [push, workflow_dispatch]

jobs:
  say_hello_job:
    runs-on: ubuntu-latest
    steps:
    - name: hello world actions
      uses: u0324020/actions-helloword@v1.0.2
      with:
        strecho: helloworld
