name: helloworld_workflow

on: [push, workflow_dispatch]

jobs:
  say_hello_job:
    runs-on: ubuntu-latest
    steps:
    - uses: toko-bifrost/ms-teams-deploy-card@master
      with:
        github-token: ${{ github.token }}
        webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        environment: dev # won't be included in the card if none
        timezone: Asia/Taipei
        view-status-action-text: View in Actions
        review-diffs-action-text: Review Commit Diffs
        
    - name: hello world actions
      uses: u0324020/actions-helloword@v1.0.0
      with:
        strecho: helloworld
        numecho: 123
